name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: secondlife/action-autobuild@v4
        with:
          platform: common
      - uses: secondlife/action-autobuild-release@v3
        if: startsWith(github.ref, 'refs/tags/v')
